server:
  port: 9090

spring:
  application:
    name: AUTH-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:default}
      port: ${SPRING_DATA_REDIS_PORT:default}

  config:
    import: >
      optional:configserver:http://localhost:8084,
      optional:aws-secretsmanager:spring-security-key,
      optional:aws-secretsmanager:microservice-db-config,
      optional:aws-secretsmanager:ecommerce-app/mail-config,
      optional:aws-secretsmanager:ecommerce-app/redis-config


  security:
    secret:
      key: ${SPRING.SECURITY.SECRET.KEY:default-local-secret}
    access:
      token:
        expiration: ${SPRING.SECURITY.ACCESS.TOKEN.EXPIRATION:3600000}
    refresh:
      token:
        expiration: ${SPRING.SECURITY.REFRESH.TOKEN.EXPIRATION:604800000}
    verification:
      code:
        ttl:
          minutes: ${SPRING.SECURITY.VERIFICATION.CODE.EXPIRATION:15}


  mail:
    host: ${SPRING.MAIL.HOST:}
    port: ${SPRING.MAIL.PORT:}
    username: ${SPRING.MAIL.USERNAME:}
    password: ${SPRING.MAIL.PASSWORD:}
    protocol: ${SPRING.MAIL.PROTOCOL:}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

aws:
  access-key-id: ${AWS_SECRET_KEY_ID}
  secret-access-key: ${AWS_SECRET_VALUE}
  region: ${AWS_REGION}
  db-config-secret-name: ${AWS_DB_CONFIG_SECRET_NAME}

logging:
  level:
    org:
      springframework: DEBUG
  file:
    name: logs/auth-service.log
  charset:
    file: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss


