server:
  port: 8083


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates:  #Yönlendirme kurallarını belirler. Örneğin, Path=/users/** ifadesi, /api/v1/products/** ile başlayan tüm istekleri bu rotaya yönlendirir.
            - Path=/api/v1/products/**


        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler. Örneğin,
            - Path=/api/v1/orders/**


        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler.
            - Path=/api/v1/inventories/**


        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler.
            - Path=/api/v1/payments/**


        - id: CARGO-SERVICE
          uri: lb://CARGO-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler.
            - Path=/api/v1/cargo/**

        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler.
            - Path=/api/v1/customers/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE  #Hedef servis URI'si belirtilir. lb:// ile başlayan URI'ler, yük dengeleyici (load balancer) kullanılarak mikroservislere yönlendirilir.
          predicates: #Yönlendirme kurallarını belirler.
            - Path=/api/v1/auth/**


  config:
    import: optional:configserver:http://localhost:8084

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/spring-microservice

logging:
  level:
    org.springframework.cloud.gateway : DEBUG #Gateway için log seviyesini belirler.




#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka
