server:
  port: 8082

spring:
  application:
    name: INVENTORY-SERVICE

  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #redis config
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  config:
    import: optional:configserver:http://localhost:8084

management:
  #Bu ayar, Actuator tarafından sunulan HTTP endpoint'lerini (veya yönlendiricilerini) hangi durumda açacağını belirtir. Özellikle web altındaki exposure bölümü, bu endpoint'lerin hangi koşullarda dış dünyaya (HTTP istemcilerine) açılacağını tanımlar.
  endpoints:
    web:
      exposure:
        include: health  # Yani, /actuator/health endpoint'i HTTP isteklerine cevap verecektir.
  #Bu ayar, uygulamanızın sağlık (health) endpoint'inin sağladığı raporlarda detaylı bilgilerin gösterilip gösterilmeyeceğini belirtir. Özellikle health altındaki show-details parametresi, bu endpoint'in ne kadar ayrıntılı bilgi sunacağını kontrol eder.
  endpoint:
    health:
      show-details: always # : Sağlık endpoint'inin sağladığı raporlarda detaylı bilgilerin gösterilip gösterilmeyeceğini belirtir.
  tracing: #zipkin Tracing (İzleme) Yapılandırması
    sampling:
      probability: 1.0  #tüm isteklerin izleneceği anlamına gelir

#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
