server:
  port: 8082

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672


rabbit:
  mq:
    exchange:
      name: e_commerce_exchange
    routing:
      key: e_commerce_routing_key
      create:
        product: e_commerce_routing_key_create_product
    queue:
      name: e_commerce_queue
      create:
        product: e_commerce_queue_create_product

  config:
    import: optional:configserver:http://localhost:8084

#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


